### ISSUE TITLE
uart spare part: complement docs for configuration

### ISSUE THREAD

**Issue by atesin** [lcgamboa/picsimlab_docs#1]
hi... you sim got me amazed.... no more cables hanging from my desk, or delays in flasing my arduinos, or risk of brick or burn while developing and testing =D

i had a silly discovery scratching my head and hitting against my pc, i even filled an issue in pcsimlab (now closed)

please add in your docs the arduino additional parameters for serial configurarion and uart virt device = **8N1**
in addition, please state somewhere that you need the same configuration **in all these 3 places**: sofwareserial (the sketch), uart virt module, and endpoint (terminal, pc, com port, device, etc)

thanks

**Comment by lcgamboa** [comment]
Docs updated to include the information of 8N1 format used in PICSimLab serial components.
